config/routes.rb
NeumannBiz::Application.routes.draw do

    match 'impressum' => 'pages#impressum'
    
    match 'data_munging' => 'data_munging#index'
    get "data_munging/about"
    get "data_munging/plain_text"
    get "data_munging/csv"
    get "data_munging/word"
    get "data_munging/excel"
    get "data_munging/pdf"
    get "data_munging/html"
    get "data_munging/xml"
    get "data_munging/hocr"
    get "data_munging/odf"
    get "data_munging/tei"
    get "data_munging/wikipedia_dump"
    get "data_munging/static_data"
    get "data_munging/dynamic_data"
    get "data_munging/orm"
    get "data_munging/webframeworks"
    get "data_munging/rest"
    get "data_munging/soap"
    get "data_munging/json"
    get "data_munging/abbyy_xml"
    get "data_munging/alto_xml"
    get "data_munging/tika"
    get "data_munging/client_server"
    get "data_munging/elastic_search"
    get "data_munging/lucene_with_SOLR"
    get "data_munging/weka"
    get "data_munging/nltk"
    get "data_munging/crfplusplus"
    get "data_munging/tree_tagger"
    get "data_munging/grammatical_framework"
    
    match "document_understanding" => 'document_understanding#index'
    get "document_understanding/file_formats"
    get "document_understanding/techniques"
    
    
    match "angewandte_programmierung_in_der_computerlinguistik" => 'angewandte_programmierung_in_der_computerlinguistik#index'
    get "angewandte_programmierung_in_der_computerlinguistik/modules"
    get "angewandte_programmierung_in_der_computerlinguistik/object"
    get "angewandte_programmierung_in_der_computerlinguistik/i18n"
    
  
    resources :sources
    
    match 'vorlesung/sources/download/:id' => 'sources#download'
    match 'sources/download/:id' => 'sources#download'
    match 'vorlesung/:id' => 'sources#vorlesung'
    
    match 'uebung/sources/download/:id' => 'sources#download'
    match 'uebung/:id' => 'sources#uebung'
    
    match 'lehre/cpp-SS2011-klausurergebnisse' => 'pages#cpp-SS2011-klausurergebnisse'
    
    root :to =>'data_munging#about'
  

end

app/models/source.rb
class Source < ActiveRecord::Base
end

app/controllers/sources_controller.rb
#coding: utf-8
class SourcesController < ApplicationController
    
    before_filter :minimal_security?, :except=> [:index, :show, :download, :vorlesung, :uebung]
  # GET /sources
  # GET /sources.xml
  def index
    @sources = Source.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sources }
    end
  end

  # GET /sources/1
  # GET /sources/1.xml
  def show
    @source = Source.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @source }
      format.json  { render :json => @source }
    end
  end

  # GET /sources/new
  # GET /sources/new.xml
  def new
    @source = Source.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @source }
    end
  end

  # GET /sources/1/edit
  def edit
    @source = Source.find(params[:id])
  end

  # POST /sources
  # POST /sources.xml
  def create
    @source = Source.new(params[:source])

    respond_to do |format|
      if @source.save
        format.html { redirect_to(@source, :notice => 'Source was successfully created.') }
        format.xml  { render :xml => @source, :status => :created, :location => @source }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sources/1
  # PUT /sources/1.xml
  def update
    @source = Source.find(params[:id])

    respond_to do |format|
      if @source.update_attributes(params[:source])
        format.html { redirect_to(@source, :notice => 'Source was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.xml
  def destroy
    @source = Source.find(params[:id])
    @source.destroy

    respond_to do |format|
      format.html { redirect_to(sources_url) }
      format.xml  { head :ok }
    end
  end
  
  def download
      @source = Source.find(params[:id])
      send_data(@source.code, :filename => "#{@source.title}.#{@source.language}")
  end
  
  def vorlesung
      @id = params[:id]
      @sources = Source.find(:all).select {|s| s.title =~ /Vorlesung #{@id} /}
  end
  
  def uebung 
      @id = params[:id]
      @sources = Source.find(:all).select {|s| s.title =~ /Übung #{@id} /}
  end

  private
  
    def minimal_security?
        
        name = params[:name] || session[:name]
        password = params[:password] || session[:password]
        
        user = User.find_by_name(name)
        
        puts user
        
        unless user && user.password == password 
            flash[:alert] = "Nicht erlaubt."
            redirect_to(sources_url)
        end
        
        session[:name] = name
        session[:password] = password
        
    end 
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/sources/_form.html.haml
= form_for @source do |f|
  -if @source.errors.any?
    #error_explanation
      %h2= "#{pluralize(@source.errors.count, "error")} prohibited this source from being saved:"
      %ul
        - @source.errors.full_messages.each do |msg|
          %li= msg

  .field
    %h3= f.label :title
    = f.text_field :title
  .field
    %h3= f.label :author
    = f.text_field :author
  .field
    %h3= f.label :tag
    = f.text_field :tag
  .field
    %h3= f.label :description
    = f.text_area :description
  .field
    %h3= f.label :language
    = f.text_field :language
  .field
    %h3= f.label :code
    = f.text_area :code
  .actions
    = f.submit 'Save'

app/views/sources/edit.html.haml
%h1 Editing source

= render 'form'

= link_to 'Show', @source
\|
= link_to 'Back', sources_path

app/views/sources/index.html.haml
%h1 Quelltexte
%section
	- @sources.each do |source|
		%article
			%header
				%h2=source.title
			%p=source.description
			~raw highlight source.code, source.language
			%footer
				= link_to 'Download', "sources/download/#{source.id}"
				= link_to 'Show', source
				-if allowed?
					= link_to 'Edit', edit_source_path(source)
					|
					= link_to 'Destroy', source, :confirm => 'Are you sure?', :method => :delete
-if allowed?
	= link_to 'New Source', new_source_path

app/views/sources/new.html.haml
%h1 New source

= render 'form'

= link_to 'Back', sources_path

app/views/sources/show.html.haml
%p#notice= notice
%p
	%b Title:
	= @source.title
%p
	%b Author:
	= @source.author
%p
	%b Tag:
	= @source.tag
%p
	%b Description:
	= @source.description
%p
	%b Language:
	= @source.language
%p
	%b Code:
	~sanitize highlight @source.code, @source.language

= link_to 'Back', sources_path

app/views/sources/uebung.html.haml
%h1
	Höhere Programmierung in der Computerlinguistik mit C++ - Übung 
	=@id
=link_to 'Zurück', '/cpp'
- @sources.each do |source|
	%article
		%header
			%h2=source.title
		%p=source.description
		~raw sanitize highlight source.code, source.language
		%footer
			= link_to 'Download', "sources/download/#{source.id}"
			|
			= link_to 'Show', source
=link_to 'Zurück', '/cpp'

app/views/sources/vorlesung.html.haml
%h1
	Höhere Programmierung in der Computerlinguistik mit C++ - Vorlesung 
	=@id
=link_to 'Zurück', '/cpp'
- @sources.each do |source|
	%article
		%header
			%h2=source.title
		%p=source.description
		~sanitize highlight source.code, source.language
		%footer
			= link_to 'Download', "sources/download/#{source.id}"
			|
			= link_to 'Show', source
=link_to 'Zurück', '/cpp'